### router.get('/', ctrl.getAllContacts);
GET http://localhost:3000/api/contacts

### router.get('/:contactId', ctrl.getContactById);
GET http://localhost:3000/api/contacts/64fdc427300cd41db445a416


### router.post('/', validatedContacts(schemaValidation), ctrl.createContact);
POST http://localhost:3000/api/contacts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDg0ZWE2ZmQzM2U0NzU4ZjMyMTY1NiIsImlhdCI6MTY5NTA0OTM0NywiZXhwIjoxNjk1MTMyMTQ3fQ.l5D8ArqoC1cXkZP14XvjyMFaTTZ4Ls_cd3GSknR3UWA

{
  "name": "Jane Vorobey",
  "email": "qweqwe@qw.com",
  "phone": "(999) 321-7654",
  "favorite": true
}

### router.delete('/:contactId', ctrl.removeContactById);
DELETE http://localhost:3000/api/contacts/64fdc427300cd41db445a419

### router.put('/:contactId', ctrl.updateContactById);
PUT http://localhost:3000/api/contacts/64ff643a1f8d1b4082e273e2
Content-Type: application/json

{
  "name": "Janete Vorobey",
  "email": "qweqwe@qw.com",
  "phone": "(999) 321-7654",
  "favorite": true
}

### router.patch('/:contactId/favorite', ctrl.updateStatusContact);
PATCH http://localhost:3000/api/contacts/64ff643a1f8d1b4082e273e2/favorite
Content-Type: application/json

{
  "favorite": true
}

### Register User
### authRouter.post('/:register', authCtrl.register);
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "mango@qw.com",
  "password": "111111"
}

### Login User
### authRouter.post('/:login', authCtrl.login);
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "mango@qw.com",
  "password": "111111"
}

> {%

 %}


### Current User
### authRouter.get('/:curent', authCtrl.getCurrent);
GET http://localhost:3000/api/auth/current
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDk1NzI1MDlhOTQ3OTU0ZDk0NDIwNCIsImlhdCI6MTY5NTExMTcyMSwiZXhwIjoxNjk1MTk0NTIxfQ.zaSD7SM8p3YehB0ac1GCPWMAnqNu5Vz-K9qQy7ogv6k

### Logout User
### authRouter.post('/:logout', authCtrl.logout);
POST http://localhost:3000/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDk1NzI1MDlhOTQ3OTU0ZDk0NDIwNCIsImlhdCI6MTY5NTExMTEwMywiZXhwIjoxNjk1MTkzOTAzfQ.xCFNIk5k_IlcZz40V6cHdthriOr3kk2KAC9Kc8rfQvY

### authRouter.patch('/:current/subscription', authCtrl.patchSubscription);
PATCH http://localhost:3000/api/auth/current/subscription
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDk1NzI1MDlhOTQ3OTU0ZDk0NDIwNCIsImlhdCI6MTY5NTExMzU2NywiZXhwIjoxNjk1MTk2MzY3fQ.C8veIQkRBREy3JZ3cp6nCpzLUL6oRwzWqKhLW3mIT2s
Content-Type: application/json

{
  "subscription": "pro"
}
